;;; anvil-init.el --- minimal anvil bootstrap -*- lexical-binding: t; -*-
;; Generated by install.sh on 2026-04-28 06:12:28
;; Regenerating is safe — this file carries no user state.

(add-to-list 'load-path "/Users/ken/.emacs.d/external-packages/anvil.el")
(require 'anvil)
;; anvil-server-commands holds anvil-server-start / -stop etc.  It is
;; autoload-cookied, but manual-install (plain add-to-list + require) does
;; not generate loaddefs, so we require it explicitly.
(require 'anvil-server-commands)
(anvil-enable)
(anvil-server-start)

(provide 'anvil-init)
;;; anvil-init.el ends here
